# Server Port ??(client ?? ????? ???? ??? ??)
server:
  port: 8000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: 1st-service
          # uri? http://ip:port? ?? ???? ??? ? ???
          # ????? ??? ?? ???? ???? service? name?? ????.
          # lb:// ? ??? ?? ???? ???? ??
          uri: lb://1ST-SERVICE
          predicates:
            # ??? ??? ??? ?? ? ?? ??? ??? ?? ???.
            - Path=/first-service/**
          # ?? ????? ???? ?? ?? ?? ??? filter ??? ? ? ??.
          filters:
            # /first-service/health ??? /health? ????? ??
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
            # ?? : 'first-request' ??? 'first-value' ?? ???? ??
            - AddRequestHeader=first-request, first-request-value
            # ?? : 'first-response' ??? 'first-value' ?? ???? ??
            - AddResponseHeader=first-response, first-response-value
        - id: 2st-service
          uri: lb://2ST-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
            - AddRequestHeader=second-request, second-request-value
            - AddResponseHeader=second-response, second-response-value
eueka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka